### ISSUE TITLE
include() in pattern data only working on initial build

### ISSUE THREAD

**Issue by alamowo** [aleksip/plugin-data-transform#16]
Hi,

when working on a pattern in which I include another pattern using the [pattern].yml or [pattern].json file, it only works on the initial build of the pattern lab. When running `php core/console --watch` and i change that data file or simply some css that makes PL recompile to the public folder, I only get `Array` as output. 

Then I have to quit the PL watch task an rerun it.

Example YAML:
```yml
mol_accordion_elements:
  '1':
    title: A File
    icon: 'icon_download'
    content:
      include():
        pattern: atoms-file
        with:
          file:
            filename: file.pdf
            filesize: 96KB
            permalink: http://test.com/file.pdf
        only: true
```
